# Generated by Django 6.1 on 2026-09-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_category_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
